[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"

[[bin]]
name = "day_1"
path = "src/day_1/main.rs"

[[bin]]
name = "day_2"
path = "src/day_2/main.rs"
